#
# This file is part of phpFastCache.
#
# @license MIT License (MIT)
#
# For full copyright and license information, please see the docs/CREDITS.txt file.
#
# @author Georges.L (Geolim4)  <contact@geolim4.com>
# @author Contributors  https://github.com/PHPSocialNetwork/phpfastcache/graphs/contributors
#
os: linux
dist: bionic
language: php

services:
  - memcached
  - redis
cache:
  directories:
    - $HOME/pecl_cache
php:
  - 8.0
  - 8.1
  - 8.2
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - sudo apt remove cmake
  - pip install cmake --upgrade
  - phpenv config-add bin/ci/php_common.ini
  - phpenv config-rm xdebug.ini
  - composer install
  - composer require phwoolcon/ci-pecl-cacher -n
  - "./bin/ci/scripts/install_ssdb.sh || echo \"SSDB install failed\""
  - "./bin/ci/scripts/install_couchbase.sh || echo \"Couchbase install failed\""
  - "./bin/ci/scripts/setup_gcp.sh || echo \"GCP setup failed\""
  - "pecl channel-update pecl.php.net || echo \"PECL Channel update failed\""
  - "yes | ./vendor/bin/ci-pecl-install memcache || echo \"PECL Memcache install failed\""
  - "yes | ./vendor/bin/ci-pecl-install memcached || echo \"PECL Memcached install failed\""
  - "yes | ./vendor/bin/ci-pecl-install couchbase-3.2.2 couchbase || echo \"PECL Couchbase install failed\"" # @todo UPGRADE TO COUCHBASE 4.x.x once we upgraded from Bionic to Focal
install:
  - ./bin/ci/scripts/install_dependencies.sh

script:
  - composer run-script quality
  - composer run-script tests
